In [7]:
import numpy as np

x=np.ones([100, 10,5])

print(x+x/2)
print (np.shape(x))

[[[1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  ...
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  ...
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  ...
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]]

 ...

 [[1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  ...
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  ...
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]]

 [[1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  ...
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]
  [1.5 1.5 1.5 1.5 1.5]]]
(100, 10, 5)
